/**
 * agents/actionAgent.js
 * Agent 6: Action Agent
 * The execution layer — posts structured dashboard comment to GitLab MR,
 * posts individual suggestion comments for security fixes,
 * applies labels, sends executive email brief.
 */

import logger from '../middleware/logger.js';
import {
  postMRComment,
  updateMRLabels,
} from '../tools/gitlabClient.js';
import { sendMRBrief } from '../tools/emailer.js';

const LABEL_MAP = {
  LOW: 'flux:cleared',
  MEDIUM: 'flux:review-required',
  HIGH: 'flux:blocked',
};

const STATUS_EMOJI = {
  LOW: '✅',
  MEDIUM: '⚠️',
  HIGH: '🚨',
};

export async function takeAction({ mr, project, context, audit, docs, risk, green }) {
  logger.info(`[Agent 6: Action Agent] Starting for MR !${mr.iid}`);
  const startTime = Date.now();

  const projectId = context?.projectId || project?.id || mr.project_id;
  const mrIid = mr.iid;
  const riskLabel = risk?.label || 'MEDIUM';

  const results = {
    commentPosted: false,
    commentId: null,
    suggestionsPosted: 0,
    labelApplied: null,
    emailSent: false,
  };

  // ── 1. Build and post dashboard comment ─────────────────────────────────
  try {
    const commentBody = buildDashboardComment({ mr, context, audit, docs, risk, green });
    const note = await postMRComment(projectId, mrIid, commentBody);
    results.commentPosted = true;
    results.commentId = note?.id;
    logger.info(`[Agent 6] Dashboard comment posted, note id: ${note?.id}`);
  } catch (err) {
    logger.error(`[Agent 6] Failed to post dashboard comment: ${err.message}`);
  }

  // ── 2. Post individual finding comments for critical/high severity ────────
  // Note: Using regular MR comments (not inline discussions) to avoid
  // requiring exact GitLab diff position data (line_code, base_sha, etc.)
  const findings = audit?.findings || [];
  const actionableFindings = findings.filter(f =>
    (f.severity === 'critical' || f.severity === 'high') && f.fixedCode
  );

  for (const finding of actionableFindings.slice(0, 8)) {
    try {
      const emoji = finding.severity === 'critical' ? '🔴' : '🟠';
      const body = [
        `## ${emoji} Security Finding — ${finding.severity.toUpperCase()}`,
        '',
        `**Type:** \`${finding.type || 'unknown'}\` | **CWE:** ${finding.cweId || 'N/A'} | **File:** \`${finding.file || 'unknown'}\`${finding.line ? ` (line ${finding.line})` : ''}`,
        '',
        `**Issue:** ${finding.description}`,
        '',
        '**Vulnerable code:**',
        '```',
        finding.originalCode || '',
        '```',
        '',
        '**Suggested fix:**',
        '```',
        finding.fixedCode,
        '```',
        '',
        `_Auto-generated by FluxSentinel AI · Apply this fix to resolve the ${finding.severity} severity issue_`,
      ].join('\n');

      await postMRComment(projectId, mrIid, body);
      results.suggestionsPosted++;
      logger.info(`[Agent 6] Finding comment posted: ${finding.severity} ${finding.type}`);
    } catch (err) {
      logger.warn(`[Agent 6] Finding comment failed (non-fatal): ${err.message}`);
    }
  }

  // ── 3. Apply GitLab labels ───────────────────────────────────────────────
  try {
    const label = LABEL_MAP[riskLabel] || 'flux:review-required';
    await updateMRLabels(projectId, mrIid, [label, 'flux-sentinel-reviewed']);
    results.labelApplied = label;
    logger.info(`[Agent 6] Labels applied: ${label}`);
  } catch (err) {
    logger.error(`[Agent 6] Label update failed: ${err.message}`);
  }

  // ── 4. Send executive email brief ────────────────────────────────────────
  try {
    const mrUrl = context?.mrDetails?.web_url || `${process.env.GITLAB_API_URL?.replace('/api/v4', '')}/${mr.project_id}/-/merge_requests/${mrIid}`;
    const emailResult = await sendMRBrief({ mr: context?.mrDetails || mr, project, audit, risk, green, mrUrl });
    results.emailSent = emailResult.sent;
    if (emailResult.sent) {
      logger.info(`[Agent 6] Email sent, id: ${emailResult.id}`);
    }
  } catch (err) {
    logger.error(`[Agent 6] Email send failed: ${err.message}`);
  }

  logger.info(`[Agent 6: Action Agent] Done in ${Date.now() - startTime}ms.`, results);
  return results;
}

// ─── Dashboard Comment Builder ────────────────────────────────────────────────

function buildDashboardComment({ mr, context, audit, docs, risk, green }) {
  const riskLabel = risk?.label || 'MEDIUM';
  const score = risk?.score ?? 0;
  const emoji = STATUS_EMOJI[riskLabel] || '⚠️';
  const findings = audit?.findings || [];
  const critCount = findings.filter(f => f.severity === 'critical').length;
  const highCount = findings.filter(f => f.severity === 'high').length;
  const medCount = findings.filter(f => f.severity === 'medium').length;
  const lowCount = findings.filter(f => f.severity === 'low').length;
  const timestamp = new Date().toUTCString();

  const agentRows = [
    {
      agent: '🧠 Context Engine',
      status: context?.error ? '❌ Error' : '✅ Done',
      detail: context?.summary ? context.summary.slice(0, 100) + '...' : 'Context loaded',
    },
    {
      agent: '🔐 Security Auditor',
      status: audit?.error ? '❌ Error' : (audit?.passed ? '✅ Passed' : '🔴 Issues Found'),
      detail: `${findings.length} finding(s): ${critCount} critical · ${highCount} high · ${medCount} medium · ${lowCount} low${audit?.consensus ? ` · Verdict: ${audit.verdict}` : ''}`,
    },
    {
      agent: '📚 Docs Guardian',
      status: docs?.error ? '❌ Error' : (docs?.updated ? '✅ Wiki Updated' : '✅ Docs OK'),
      detail: docs?.summary || 'No documentation gaps detected',
    },
    {
      agent: '📊 Risk Scorer',
      status: risk?.error ? '❌ Error' : `${emoji} ${riskLabel} RISK`,
      detail: `Score: ${score}/100 · ${risk?.recommendation || 'Review recommended'} · ${(risk?.reasoning || '').slice(0, 80)}`,
    },
    {
      agent: '🌱 Green Sentinel',
      status: green?.error ? '❌ Error' : '♻️ Tracked',
      detail: green?.impact || `Saved ${green?.pipelinesSaved ?? 0} pipelines · ${green?.co2Saved ?? 0}g CO₂`,
    },
    {
      agent: '⚡ Action Agent',
      status: '✅ Executing',
      detail: 'Posting comments, applying labels, sending email brief',
    },
  ];

  const agentTable = [
    '| Agent | Status | Detail |',
    '|-------|--------|--------|',
    ...agentRows.map(r => `| ${r.agent} | ${r.status} | ${r.detail} |`),
  ].join('\n');

  const findingSummary = findings.length > 0
    ? [
        '',
        '### 🔍 Security Findings',
        '',
        '| Severity | Type | File | Description | Source | Auto-Fix |',
        '|----------|------|------|-------------|--------|----------|',
        ...findings.slice(0, 15).map(f =>
          `| ${severityBadge(f.severity)} | \`${f.type || 'unknown'}\` | \`${(f.file || 'unknown').split('/').pop()}\` | ${(f.description || '').slice(0, 55)} | ${confirmedByBadge(f.confirmedBy)} | ${f.fixedCode ? '✅ Yes' : '—'} |`
        ),
        findings.length > 15 ? `\n_...and ${findings.length - 15} more findings._` : '',
      ].join('\n')
    : '\n> ✅ **No security issues found.** Code passed all checks from both AI models and regex scanner.';

  const docsSection = docs?.updated
    ? `\n### 📝 Documentation Auto-Updated\nWiki pages updated: ${(docs.updatedPages || []).map(p => `\`${p}\``).join(', ')}`
    : '';

  // ── Multi-Model Consensus Section ──
  const consensusData = audit?.consensus;
  const consensusSection = consensusData
    ? [
        '',
        '### 🤖 Multi-Model Consensus',
        '',
        '| Metric | Value |',
        '|--------|-------|',
        `| Models Used | Claude claude-sonnet-4-6 + Gemini 1.5 Flash |`,
        `| Agreement Rate | **${Math.round((consensusData.agreementRate || 0) * 100)}%** |`,
        `| Confirmed by Both | ${consensusData.confirmedByBoth ?? 0} finding(s) 🤝 |`,
        `| Claude Only | ${consensusData.claudeOnly ?? 0} finding(s) 🔵 |`,
        `| Gemini Only | ${consensusData.geminiOnly ?? 0} finding(s) 🟢 |`,
        `| Regex / CVE Detected | ${consensusData.regexDetected ?? 0} finding(s) ⚡ |`,
        `| High Confidence (≥90%) | ${consensusData.highConfidenceFindings ?? 0} finding(s) |`,
        `| Verdict | **${audit?.verdict || 'REVIEW'}** |`,
      ].join('\n')
    : '';

  return `## ⚡ FluxSentinel AI — MR Analysis Report

> **${emoji} ${riskLabel} RISK** · Score: **${score}/100** · Recommendation: **${(risk?.recommendation || 'review').toUpperCase().replace('-', ' ')}**
> 
> _Analyzed by FluxSentinel AI (Claude + Gemini multi-model consensus) at ${timestamp}_

---

### 🤖 Agent Results

${agentTable}
${findingSummary}
${consensusSection}
${docsSection}

---
<sub>⚡ FluxSentinel AI · Autonomous DevSecOps Orchestrator · ${findings.filter(f => f.fixedCode).length} auto-fix suggestion(s) posted above</sub>`;
}

function severityBadge(severity) {
  switch ((severity || '').toLowerCase()) {
    case 'critical': return '🔴 Critical';
    case 'high': return '🟠 High';
    case 'medium': return '🟡 Medium';
    default: return '🔵 Low';
  }
}

function confirmedByBadge(confirmedBy) {
  switch ((confirmedBy || '').toLowerCase()) {
    case 'both': return '🤝 Both';
    case 'claude': return '🔵 Claude';
    case 'gemini': return '🟢 Gemini';
    case 'regex': return '⚡ Regex';
    case 'osv': return '⚡ CVE';
    default: return '🔵 Claude';
  }
}
